### ISSUE TITLE
Crash on Left pane reduced length invalid values

### ISSUE THREAD

**Issue by petrspelos** [Seeriis/SerrisCodeEditor#11]
So I slightly increased the "Left pane reduced length" and the application crashed. 🤔 🤔 🤔 🤔 🤔 

I think there should be some limits or at least the Exception should be caught...

![Capture22](https://user-images.githubusercontent.com/21304428/92966879-da547b80-f467-11ea-9aff-a59abfce0721.PNG)

**Comment by petrspelos** [comment]
Update: If you set it to -1 you cannot use the editor anymore, since it will crash on startup. 🤔 🤔 🤔 🤔 🤔

**Comment by quinchs** [comment]
Sir i have the same problem. my fix was to uninstall it and install VS2019. Hope this helps!

**Comment by petrspelos** [comment]
Yeah, but VS2019 does not have the StackOverflow integration, which I really like. 🤔

**Comment by quinchs** [comment]
Well, I suggest either having a web browser open or writing a VS extension to have a browser tab

**Comment by DraxCodes** [comment]
Thanks for the fix @quinchs worked perfectly for me too. Turns out I can have Firefox open on the left side of the screen for StackOverflow 🤔 Windows 10 snapping works well.,

**Comment by petrspelos** [comment]
Turns out you can reset the app settings in Windows. I now have my Serris working again

![fix](https://user-images.githubusercontent.com/21304428/92967557-045a6d80-f469-11ea-91a8-6926686cc43d.PNG)

**Comment by quinchs** [comment]
The issue lies [Here](https://github.com/Seeriis/SerrisCodeEditor/blob/master/SerrisCodeEditor/SerrisCodeEditor/Xaml/Views/SettingsManager.xaml.cs#L234 "beep beep lettuce") with not checking for absurd values or integer over/underflows
